#!/bin/bash
set -eux

year=$1
output_dir=$2

if [ ! -d "$output_dir" ]; then
  echo "$output_dir does not exist."
  exit 1;
fi

dir=$(dirname "$0")

source $dir/fips_codes
source $dir/alpha_codes
source $dir/download_files

place_files=()
place_url="https://www2.census.gov/geo/tiger/TIGER$year/PLACE"
for code in "${fips_codes[@]}"; do
  place_files+=("tl_${year}_${code}_place.zip")
done
download $place_url $output_dir "${place_files[@]}"

county_files=("tl_2024_us_county.zip")
county_url="https://www2.census.gov/geo/tiger/TIGER$year/COUNTY"
download $county_url $output_dir "${county_files[@]}"

state_files=("tl_2024_us_state.zip")
state_url="https://www2.census.gov/geo/tiger/TIGER$year/STATE"
download $state_url $output_dir "${state_files[@]}"

census_designated_place_files=()
census_designated_places_url="https://tigerweb.geo.census.gov/tigerwebmain/Files/bas25"
for code in "${alpha_codes[@]}"; do
  census_designated_place_files+=("tigerweb_bas25_cdp_${year}_acs${year: -2}_${code}.html")
done
download $census_designated_places_url $output_dir "${census_designated_place_files[@]}"
